FROM jekyll/jekyll:3.8.1

WORKDIR /home
# RUN mkdir columns
RUN git clone --branch develop https://github.com/andrew0928/columns.chicken-house.net columns
RUN chmod 777 columns

WORKDIR /srv/jekyll


# ENTRYPOINT [ "jekyll", "s", "--watch", "--draft", "00incremental", "--source", "/home/columns.chicken-house.net", "--destination", "/tmp", "--unpublished" ]

ENTRYPOINT [ "ping", "127.0.0.1" ]